### ISSUE TITLE
앱 심사 리젝 관련 이슈

### ISSUE THREAD

**Issue by syss220211** [APPSCHOOL3-iOS/final-zeno#376]
리젝 사유 

1. Guideline 5.1.2 - Legal - Privacy - Data Use and Sharing 
![Screenshot-1114-095622](https://github.com/APP-iOS2/final-zeno/assets/110394722/38ac9d35-e2ba-490b-a851-535495134eb6)

사진 요청에 대한 이유, 어떻게 사용되는지에 대한 상세 설명이 없는 것 같아서 리젝 먹은것 같습니다.
(https://gyuios.tistory.com/174)
참고하여 plist에서 문구 수정하면 심사 통과 될 것 같아요.

2. Guideline 5.1.1 - Legal - Privacy - Data Collection and Storage
![Screenshot-1114-095423](https://github.com/APP-iOS2/final-zeno/assets/110394722/d55a801d-1ed0-4faa-9983-435c3adcee6b)

애플이 말하고 있는 내용)
우리는 당신의 앱이 당신의 앱의 핵심 기능과 직접적으로 관련이 없는 개인 정보로 등록할 것을 요구한다는 것을 알아챘습니다. 구체적으로, 다음의 필드 또는 작업은 필요하지만 당신의 앱의 핵심 기능과 직접적으로 관련이 없는 것으로 보입니다 -> 성별
이 문제를 해결하려면 앱과 관련이 없는 필수 필드를 모두 제거하거나 해당 필드를 선택 사항으로 지정하십시오. 등록 중에 요청된 정보는 앱이 제공하는 기능과 관련이 있어야 합니다.

-> 성별을 받는 이유를 받는 뷰에서 명시해주어야 할 것 같아요.
-> 먼저 성별에 따른 차별점이 무엇이있는지랑 왜 성별을 받고 있는지 명시하면 통과될거 같습니다.

3. Guideline 4.8 - Design - Sign in with Apple
귀하의 앱은 타사 로그인 서비스를 사용하지만 Apple 로그인을 제공하지 않습니다. 계정 인증을 위해 타사 로그인 서비스를 사용하는 앱은 앱스토어 사용자가 기대하는 로그인 경험을 제공하기 위해 동등한 옵션으로 Apple 로그인을 사용자에게 제공해야 합니다.

-> 애플 로그인 추가하면 해결될 것 같습니다~

**Comment by gnksbm** [comment]
2번 수정사항 release05에 적용했습니다
